#include "mbt.h"

MB_BEGIN_INPUTS( MBT, MBUSTiny )
  MB_INPUT( 42, readLed )
MB_END_INPUTS( MBT, MBUSTiny )

MB_BEGIN_COILS( MBT, MBUSTiny )
  MB_COIL( 44, ioPIN, ioPIN )
  MB_COIL_WO( 48, ioPIN2 )
MB_END_COILS( MBT, MBUSTiny )

MB_BEGIN_REGISTERS( MBT, MBUSTiny )
  MB_REGISTER( 381, ioReg )
MB_END_REGISTERS( MBT, MBUSTiny )

MB_BEGIN_HOLDINGREGS( MBT, MBUSTiny )
  MB_HOLDINGREG( 1381, ioHoldReg, ioHoldReg)
MB_END_HOLDINGREGS( MBT, MBUSTiny )
